services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: autoedge-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_strong_Password123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Your_strong_Password123' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

  autoedge-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoedge-app
    ports:
      - "8082:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=AutoEdgeDb;User Id=sa;Password=Your_strong_Password123;TrustServerCertificate=True;Encrypt=False"
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sqlserver_data:
